[versions]
androidGradlePlugin = "8.4.0"
androidxActivity = "1.9.0"
androidxAppCompat = "1.6.1"
androidxConstraintLayout = "2.1.4"
androidxFragment = "1.6.2"
androidxNavigation = "2.7.7"
androidXTestCore = "1.5.0"
androidxTestExt = "1.1.5"
androidxTestRunner = "1.5.2"
junit4 = "4.13.2"
kotest = "5.8.1"
kotlin = "1.9.23"
leakcanary = "2.14"
material3 = "1.12.0"
timber = "5.0.1"

[libraries]
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-navigation-safeargs-gradlePlugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "androidxNavigation" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }

androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }

androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidxConstraintLayout" }

androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragment" }
androidx-fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "androidxFragment" }

androidx-navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }

androidx-test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidXTestCore" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }

junit4 = { group = "junit", name = "junit", version.ref = "junit4" }

kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }

leakcanary = { module =  "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

material3 = { group = "com.google.android.material", name = "material", version.ref = "material3" }

timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[bundles]
androidx-navigation = ["androidx-navigation-fragment", "androidx-navigation-ui"]